# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ebafeea2b3f7922f247d6b9a68fa1983f11d21849c492d5f155312031864d8532658c536a7e1ccffa17428c71b8380b986e5d8c4e6b2263fddd52f1d2fe6af3

test:
  secret_key_base: 0bab939f71b29e7ed4aa2fc285779d2140fbe9a5c61c735bb7cd88f1111099ea54e2a160ffcf4e373ab83c23d2add3f70d63c99c161156d2e76a23bc53304398

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
